### ISSUE TITLE
2019 年更新计划

### ISSUE THREAD

**Issue by wzhudev** [NG-ZORRO/today-ng-steps#17]
## App

* [ ] 更新到 8.0.0 之后版本的 ng-zorro-antd
* [ ] 使用 ng-zorro-antd 提供的更多新组件和特性
* [ ] 增加国际化内容
* [ ] 在 app 中添加版权信息和贡献者列表
* [ ] #2 中提到的其他功能
* [ ] 测试
* [ ] 使用 Now 进行部署 

## 教程

* [ ] 教程的 2.0 版本
  * [ ] 覆盖更多主题，使得内容更为全面
  * [ ] 更新图片 (由于上传过知乎服务器, 图片被压缩了)
  * [ ] 更多的功能, 比如用户登录和注册, 基于 firebase 的多端同步

## 待计划

* [ ] 接入 Firebase 以打造多端同步功能
* [ ] today-ng-mobile, today-ng-steps 的 mobile 版本, 基于 ng-zorro-mobile 和 ionic, 能够和 today-ng-steps 同步待办事项

## 文档

* [ ] 整理贡献者清单，重新撰写 README

## 周边工具

* [ ] Angular Extension Pack，一个 vscode 扩展包，帮助使用 vscode 的用户安装必要插件
---

@wendzhue 2019

PS：最近有点忙……十月份开始陆续更新

**Comment by allen2189** [comment]
编译不了了。

**Comment by ghost** [comment]
这个项目死掉了么， 尝试用最新的11.3的 antd来实现这个项目， 各种挂
